-- Notifications table + leave triggers
-- Run this in Supabase SQL editor.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null,
  actor_user_id uuid null,
  type text not null,
  entity text not null default 'leave',
  entity_id bigint not null,
  message text not null,
  url text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_created_at_idx
  on public.notifications (recipient_user_id, created_at desc);

create index if not exists notifications_recipient_is_read_idx
  on public.notifications (recipient_user_id, is_read);

-- Helper: insert admin notifications for a new leave
create or replace function public.notify_admins_leave_applied()
returns trigger
language plpgsql
as $$
declare
  emp_name text;
begin
  select e.name into emp_name
  from public.employees e
  where e.supabase_user_id = new.supabase_user_id
  limit 1;

  insert into public.notifications (recipient_user_id, actor_user_id, type, entity, entity_id, message, url)
  select
    e.supabase_user_id as recipient_user_id,
    new.supabase_user_id as actor_user_id,
    'LEAVE_APPLIED' as type,
    'leave' as entity,
    new.id as entity_id,
    coalesce(emp_name, 'Someone') || ' has applied for leave' as message,
    '/hrms/employee/leave/list?openLeaveId=' || new.id::text as url
  from public.employees e
  where e.role = 'admin'
    and e.supabase_user_id is not null;

  return new;
end;
$$;

drop trigger if exists tr_notify_admins_leave_applied on public.leaves;
create trigger tr_notify_admins_leave_applied
after insert on public.leaves
for each row
execute function public.notify_admins_leave_applied();

-- Helper: notify employee when approval_status changes to Approved/Rejected
create or replace function public.notify_employee_leave_status_changed()
returns trigger
language plpgsql
as $$
declare
  status_text text;
begin
  if new.approval_status is null then
    return new;
  end if;

  if old.approval_status is distinct from new.approval_status then
    if new.approval_status in ('Approved', 'Rejected') then
      status_text := new.approval_status;

      insert into public.notifications (recipient_user_id, actor_user_id, type, entity, entity_id, message, url)
      values (
        new.supabase_user_id,
        null,
        case when status_text = 'Approved' then 'LEAVE_APPROVED' else 'LEAVE_REJECTED' end,
        'leave',
        new.id,
        'Your leave has been ' || lower(status_text),
        '/hrms/employee/leave/list?openLeaveId=' || new.id::text
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists tr_notify_employee_leave_status_changed on public.leaves;
create trigger tr_notify_employee_leave_status_changed
after update of approval_status on public.leaves
for each row
execute function public.notify_employee_leave_status_changed();

